version: '3.6'

services:
  postgres:
    image: postgres
    volumes:
      - owasp10:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: owasp10
    ports:
      - '5432:5432'

volumes:
  owasp10: